### ISSUE TITLE
Allow setting or adding different JSON-LD contexts

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/query-ldflex#1]

**Comment by yukulele** [comment]
Hi, we also need to set a custom context, how can we help to add this feature ?

**Comment by RubenVerborgh** [comment]
Available in v2.6.0: https://github.com/solid/query-ldflex/tree/v2.6.0#adding-a-custom-json-ld-context

@yukulele Thanks for proposing help! I didn't quite know how I wanted it implemented, so I gave it a shot myself.
