### ISSUE TITLE
Issue when try to create a blank node (id value) on document

### ISSUE THREAD

**Issue by jairo-campos-JD** [solid/query-ldflex#10]
Some of the documents might not have some of the common fields like role or hasAddress as part of the vcard document. IF the node is not a blank node, we can use add or set (ldflex functions). However, there are some cases where these nodes are blank nodes, so when we want to create a blank node (like id1223334445543) it doesn't work because it will save it as an string and shouldn't be saved as one but as a blank node

We tried to use this method: data.something.hasAddress.set(blankNode()) from https://github.com/rdfjs/data-model but it doesn't work as it will save an empty array instead of :id value.

CC: @joachimvh , @RubenVerborgh 

Blank Node: the value of the node is an id that point to another object in the document

**Comment by joachimvh** [comment]
I had a look and had problems understanding the actual problem, but then I saw your mention of "an empty array", so I think there might be some syntax confusion.

First off, I tested this with the following code:
```javascript
  await user.knows.add(blankNode());
  await user.knows.image.add(blankNode());
```
Which generates the following data in the corresponding document:
```turtle
<> n0:knows [ n0:img [] ].
```
So this is actually the result I expected, hence my confusion. If by "empty array" you mean that you got something like this, let me explain:

`[]` is actually not an array in turtle, but is used to denote blank nodes. `n0:img [].` and `n0:img _:b123` have the same meaning. Inside of the brackets it is also possible to write predicates that take that given blank node as subject. Specifically, the line above is equal to the following turtle linkes:
```turtle
<> n0:knows _:b1.
_:b1 n0:img _:b2.
```
So the blank nodes do get generated, they just used a fancy syntax.

Unless you actually knew this and I'm just making a fool of myself and not seeing the issue. :D If that is the case could you provide a more extensive example? :)

**Comment by jairo-campos-JD** [comment]
Hi @joachimvh 

Ok, for example, we have a vcard, this has some fields, like name, email, role..., but when you are a new user on POD, you only have a name and you need to add the others fields like email and address. These fields point to another node and have id value https://screencast.com/t/s5jADnXu3Udf, so I don't know how to create this id to point to another node.

**Comment by joachimvh** [comment]
So those aren't blank nodes, but URIs (with a randomly generated number in them I guess?), which can be added with something like `data.something.hasAddress.set(namedNode(#id123456))`. I'm assuming you can just generate the numbers yourself, unless they're supposed to have a meaning which I don't know. @RubenVerborgh can you say whether they're supposed to be something specific?

And once you have it you can do `data.something.hasAddress.locality.set(...)` as usual.

**Comment by jairo-campos-JD** [comment]
yes it's not a blank nodes, about data.something.hasAddress.set(namedNode(#id123456)) I think will show an error because #id123456 is unknow data type on javascript

**Comment by joachimvh** [comment]
Ah yea, my mistake, I meant the string `"#id123456"`

**Comment by jairo-campos-JD** [comment]
yes but this will save it like string but on the document, it's not a string value so will show an error.

**Comment by joachimvh** [comment]
The `namedNode` around the string makes it into a URI instead of string literal.
```javascript
  await user.knows.add(namedNode('#test'));
  await user.knows.image.add(namedNode('#test2'));
```
This code will generate the following data:
```turtle
<> n0:knows :test.

:test n0:img :test2 .
```

**Comment by jairo-campos-JD** [comment]
Thank you namdeNode works fine.
