### ISSUE TITLE
Unable to read prefs.ttl from web app

### ISSUE THREAD

**Issue by pablo-rodriguez-jd** [solid/query-ldflex#14]
I'm unable to get any keys from the prefs.ttl file in my card, I'll elaborate with everything I'm doing. 

1. Fetching my card from my POD using LDFlex's data to be able to get my preferences file. (This works perfectly)

Key:

`sp:preferencesFile </settings/prefs.ttl>;`

Code:
```js
const pttl = "http://www.w3.org/ns/pim/space#preferencesFile";
const { preferences } = ProfileShape;
const user = data[this.props.webId];
const preferencesFile =  await user[pttl]
```

2. Fetching my preferences file using LDFlex's data and the file name I just got.

```js
   const preferencesTtl = data[preferencesFile.value];
```

The file gets fetched correctly as a turtle file, I checked network tab and it worked.

```
@prefix : <#>.
@prefix dct: <http://purl.org/dc/terms/>.
@prefix c: </profile/card#>.
@prefix terms: <http://www.w3.org/ns/solid/terms#>.
@prefix n0: <http://xmlns.com/foaf/0.1/>.
@prefix sp: <http://www.w3.org/ns/pim/space#>.

c:me
    terms:privateTypeIndex <privateTypeIndex.ttl>;
    terms:publicTypeIndex <publicTypeIndex.ttl>;
    n0:language "en";
    n0:mbox <mailto:pablo.rodriguez@janeirodigital.com>.
<> a sp:ConfigurationFile; dct:title "Preferences file".
```

3. I tried and get the preferences keys (some different approaches I took)

```js
const mbox =  await preferencesTtl['card:me']['foaf:mbox']
```

```js
const mbox =  await preferencesTtl['foaf:mbox']
```

I might be approaching it in a wrong way or this might be an issue with LDFlex.

**Comment by RubenVerborgh** [comment]
The problem here is the following:

> ```js
> const mbox =  await preferencesTtl['card:me']['foaf:mbox']
> ```

`card:me` is the _subject_ of the triple, but LDflex paths represent _properties_.
So you are asking LDflex for triples that look like:

```turtle
# inside of </settings/prefs.ttl>
</settings/prefs.ttl> card:me ?x.
?x foaf:mbox ?mbox.
```

whereas you actually want

```turtle
# inside of </settings/prefs.ttl>
card:me foaf:mbox ?mbox.
```

So you want an LDflex that starts from a document D to query a subject S.
But right now, we only support the case where D = S.
New feature proposed in https://github.com/solid/query-ldflex/issues/15.

**Comment by RubenVerborgh** [comment]
The above is now possible as follows:
- [`solid.data.from('https://ruben.verborgh.org/profile/')[https://data.verborgh.org/people/joachim_van_herwegen].label`](https://solid.github.io/ldflex-playground/#.from('https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F')%5Bhttps%3A%2F%2Fdata.verborgh.org%2Fpeople%2Fjoachim_van_herwegen%5D.label)

So your case is probably `solid.data.from(solid.data.user[pttl])[await solid.data.user].foaf_mbox`.
