### ISSUE TITLE
Implement compatible DELETE for node-solid-server

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/query-ldflex#18]
LDflex is coded against the SPARQL UPDATE spec, but node-solid-server does not implement that specification correctly. Specifically, it will fail with a 409 if a value does not exist, or if there are multiple matches.

A workaround for this is that we wire `.delete` in `@solid/query-ldflex` with a different handler. This handler should:
1. query all current values for the property
2. send individual patches to delete every matched value

In theory, requests in 2 could happen in parallel, but NSS does not have locking, so concurrent requests would risk damaging the file.

**Comment by RubenVerborgh** [comment]
@rubensworks Is this workaround acceptable and could/should we wire this in a subclass of the `delete` handler?

**Comment by rubensworks** [comment]
Sure, sounds like a good workaround.

I would propose to keep the current delete handler, but bind it to a different function name (e.g. `_deleteInternal`). A new `delete` handler could then be created specifically for solid that fetches query results (using `for await)`), and calls `_deleteInternal` for each query result. As long as we catch any 409 errors on this level, we should cover all cases I think.

I think this solution would only require a couple lines of code.

**Comment by RubenVerborgh** [comment]
> I would propose to keep the current delete handler, but bind it to a different function name (e.g. `_deleteInternal`).

Not bad indeed; or even `deleteSingle`, which is what it does with NSS.

> A new `delete` handler could then be created specifically for solid that fetches query results (using `for await)`)

…which, with some luck, are already loaded and will arrive from cache

> and calls `_deleteInternal` for each query result.

Check, good plan, easier than subclassing.

> As long as we catch any 409 errors on this level, we should cover all cases I think.

There shouldn't be any, since we know that all values we send exist.
I think we can just safely ignore whatever status code we get back.

> I think this solution would only require a couple lines of code.

Indeed, good thinking.

**Comment by RubenVerborgh** [comment]
Just wondering how we will ensure that all of these deletes happen before the insertion, in case a `.set` is called.

**Comment by RubenVerborgh** [comment]
Or we might just want to rewrite `.set` as well, so it first `await`s the `delete` and only then does the `.add`.

**Comment by RubenVerborgh** [comment]
Ah, got it: `current.mutationExpressions` can be a promise. Brilliant. We're all good then.

**Comment by jairo-campos-JD** [comment]
@rubensworks so the idea is to create two new functions maybe setAll that will have deleteAll add functions, deleteAll will be the function that will fetch the values and send to delete it, sound good for you?

**Comment by RubenVerborgh** [comment]
Nah, just to replace the existing `delete` function with something that indeed does delete all. The interface for the dev should remain the same.

**Comment by jairo-campos-JD** [comment]
@RubenVerborgh thank you, other question DeleteFunctionHandler extend to MutationFunctionHandler right? so I will need to create a new one on query-ldflex that will extend to MutationFunctionHandler but do you know how can I get the property of the data into this class and make the query request so will have the args to send to mutation query?

**Comment by RubenVerborgh** [comment]
> need to create a new one on query-ldflex that will extend to MutationFunctionHandler

Inheritance will not be needed, as we will be delegating to an actual `delete` handler.

> how can I get the property of the data into this class

Handlers get passed these argument in the `.handle` function.

**Comment by RubenVerborgh** [comment]
I have a fix that would work with the deviating SPARQL UPDATE implementation of node-solid-server: https://github.com/solid/query-ldflex/tree/fix/nss-patch-workaround

…if only node-solid-server's SPARQL UPDATE implementation wasn't broken in another way too: https://github.com/solid/query-ldflex/issues/18#issuecomment-466451713

**Comment by rubensworks** [comment]
I just thought of a problem where some deletions would not work anymore with this solution, namely deletion with blank nodes.

Let's say we have the following dataset:
```
```

**Comment by RubenVerborgh** [comment]
You're right, blank nodes in the source file are problematic indeed. We probably just need to give up there; unless there is only one blank node, we can delete it as last with a variable.

**Comment by rubensworks** [comment]
> We probably just need to give up there

Perhaps, yes. Hopefully this will be only a temporary fix that can be deprecated once all relevant NSS issues have been resolved in the upcoming rewrite.
