### ISSUE TITLE
Set function doesn't account for multiple values

### ISSUE THREAD

**Issue by james-martin-jd** [solid/query-ldflex#19]
Currently, if you try to use the .set function to edit a value, it performs a delete and an add, which is correct. However, if there are multiple values at the node you are deleting, a 409 error is returned from the server, since it does not know which value to delete.

Our proposed solution, working with @RubenVerborgh, is to update the set call so it will fetch all values at the requested node, then manually delete each one before inserting the new value.

**Comment by RubenVerborgh** [comment]
See #18.
