### ISSUE TITLE
Can't seem to get this to work in the browser

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [solid/query-ldflex#2]
Hi,
I have a simple html page for now and I wanted to test logging in to a Solid pod and also retrieving the name from the pod to display "Hello Joe" or whatever.

I have added the two scripts to my html
```
<script src="solid-auth-client.bundle.js"></script>
<script src="solid-query-ldflex.bundle.js"></script>
```
I can log in and out.

but if I try this in the console, 
`await solid.data['https://mistermagoo.inrupt.net/profile/card#me'].name`
I get the result `undefined`

If I try without the "card", I get an error
`Error: Could not retrieve https://mistermagoo.inrupt.net/profile/ (401)`

I think the syntax is correct, because I can enter this in the browser console
`await solid.data['https://ruben.verborgh.org/profile/#me'].name`
and get this result
`h {id: ""Ruben Verborgh"@en", toString: ƒ, toPrimitive: ƒ}`

I have tested this using your playground and that can read the name correctly, so it seems I am doing something wrong in my app.

**Comment by RubenVerborgh** [comment]
This works for me on https://solid.github.io/ldflex-playground/

Are you sure you have the latest version of solid-query-ldflex.bundle.js?
I think you are probably hitting https://github.com/comunica/comunica/issues/311, which recently got fixed.

**Comment by SQL-MisterMagoo** [comment]
Actually, I don't know what went wrong last time, but I just installed it again from npm and it now works.

Thanks for helping.

**Comment by RubenVerborgh** [comment]
Great to hear, thanks for testing!

> Is there a good place to find the latest bundle?

It is part of the npm package, in the `dist/solid-query-ldflex.bundle.js` folder. And bleeding edge is at https://solid.github.io/query-ldflex/dist/solid-query-ldflex.bundle.js
