### ISSUE TITLE
Fetch errors do not result in a promise rejection

### ISSUE THREAD

**Issue by jaxoncreed** [solid/query-ldflex#23]
When doing an asynchronous request, try/catch statements should properly catch errors, but they do not.

Example:

When running this code via a web-browswer on localhost, Tim's pod disallows requests coming from the unregistered localhost app. This is all fine, but the resulting error it triggers cannot be caught.
```
    try {
      const timName = (await data['http://www.w3.org/People/Berners-Lee/card#i'].vcard_fn).value;
      console.log(timName);
    } catch(err) {
      console.log('this should be caught')
      console.error(err);
    }
```

This yields `Uncaught (in promise) TypeError: Failed to fetch`

The same result will happen if I try to retrieve an improperly formatted ttl file

**Comment by RubenVerborgh** [comment]
Note: the above likely should not yield any errors ever, in whatever way.

**Comment by rubensworks** [comment]
Comunica probably is the root cause of this problem, see https://github.com/comunica/comunica/issues/381

**Comment by RubenVerborgh** [comment]
Root cause is apparently https://github.com/RubenVerborgh/LDflex-Comunica/pull/13.

@jaxoncreed Could you check how the above works for you with the proposed fix there?

**Comment by RubenVerborgh** [comment]
After quick testing with the original code:
- Firefox yields `TypeError: "undefined has no properties"`
- Chrome yields `Uncaught (in promise) TypeError: Failed to fetch`

So that discrepancy is also a problem.

**Comment by RubenVerborgh** [comment]
After https://github.com/RubenVerborgh/LDflex-Comunica/pull/13, also two different behaviors:
- Firefox yields `TypeError: "undefined has no properties"`
- Chrome never resolves or rejects the promise

Especially the second thing is a problem. If Chrome does not return anything to us on failure, we'd need to resolve to a timeout.

**Comment by rubensworks** [comment]
I just tested the example above in Chrome 72.0.3626.121, and `err` is properly caught every time.

However, when I test with an unknown domain, the error is only caught the very first time:
<img width="491" alt="Screen Shot 2019-05-06 at 08 30 21" src="https://user-images.githubusercontent.com/440384/57209575-4227c600-6fd9-11e9-8fdf-fe781d7d54da.png">

@RubenVerborgh Are you aware of any caching going on in LDflex?
Comunica only caches RDF sources with 200 status codes (unless there's a bug somewhere).

**Comment by akashdeep-singh** [comment]
Has there been any update on this. I've been getting it on Firefox and Chrome for 403 errors.

**Comment by RubenVerborgh** [comment]
The same problem is also present in Node, where the following code stops:

```
const ruben = data['https://ruben.verborgh.org/profile/#me'];
showPerson(ruben)

async function showPerson(person) {
  console.log(`This person is ${await person.label}`);
  console.log(`${await person.givenName} is friends with:`);
  for await (const myFriend of person.friends) {
    console.log(`- ${myFriend}`);
    for await (const otherFriend of data[`${myFriend}`].friends)
      console.log(`  - ${otherFriend}`);
  }
}
```

The error is

```
(node:14373) UnhandledPromiseRejectionWarning: Error: Could not retrieve http://www.informatik.uni-leipzig.de/~auer/foaf.rdf (404)
    at ActorRdfDereferenceHttpParse.run (/Users/ruben/Documents/UGent/Solid/solid-query-ldflex/node_modules/@comunica/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParse.js:37:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1099)
(node:14373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RubenVerborgh** [comment]
In https://github.com/solid/query-ldflex/issues/30, we are unsure whether this issue was fully fixed. Might need reproducible test cases for browsers.

**Comment by RubenVerborgh** [comment]
Indeed; tracking this in #30.
