### ISSUE TITLE
Node setup instructions incomplete

### ISSUE THREAD

**Issue by NoelDeMartin** [solid/query-ldflex#29]
I've tried to use this in a brand new app using node and my guess is there are some setup instructions missing. In particular, something about setting up the comunica engine. I've tried installing the `@comunica/actor-rdf-source-identifier-hypermedia-qpf` dependency as suggested by the error message, but that creates other issues.

I've reproduced the error in a hello world app here: https://codesandbox.io/s/solid-ldflex-hello-world-or9so?fontsize=14&module=%2Fsrc%2FApp.vue

**Comment by RubenVerborgh** [comment]
The instructions are fine, but something seems broken with the dependencies perhaps.

**Comment by rubensworks** [comment]
Seems to be related to a recent Comunica update, will look into it.
