### ISSUE TITLE
Clear cache to get edited values

### ISSUE THREAD

**Issue by matthieu-fesselier** [solid/query-ldflex#42]
Is there a way to clear the LDFlex cache?  
In Startinblox, there are many situations where the user displays a value, edit it, and needs to display it again. As we don't reload pages, we always have the old values returned by LDFlex

**Comment by rubensworks** [comment]
There should be a `clearCache` function that is exposed on path expressions: https://github.com/solid/query-ldflex/blob/ede10272df5178f1d5910f4888eee31061b7390f/src/index.js#L64-L65

**Comment by RubenVerborgh** [comment]
(And the `document` attribute is optional.)

**Comment by matthieu-fesselier** [comment]
Works great, thanks!
