### ISSUE TITLE
Unable to create new web access control resources

### ISSUE THREAD

**Issue by jairo-campos-JD** [solid/query-ldflex#5]
Unable to create new web access control resources

Full featured write to a solid pod means the ability to manipulate web access control rules, adding, updating, and removing wac resources as needed. In the current node solid server, we are unable to create new acl files. However, if ldflex is going to work across solid implementations, it shouldn’t be married to the underlying implementation (in this case files), otherwise you have to change the code if you switch to a different solid server that doesn’t use file based ACL.

**Comment by RubenVerborgh** [comment]
Should be covered inn #7, possibly #9.
