### ISSUE TITLE
Replace <> in the container to <http://xxxxx> before querying

### ISSUE THREAD

**Issue by linonetwo** [solid/query-ldflex#51]
https://forum.solidproject.org/t/ls-ldp-container-using-ldflex/2522

Can there be a config to do such replacement?

**Comment by linonetwo** [comment]
Use `data[https://linonetwo.solid.authing.cn/public/tiddlywiki/main/][http://www.w3.org/ns/ldp#contains]` instead of `data[https://linonetwo.solid.authing.cn/public/tiddlywiki/main][http://www.w3.org/ns/ldp#contains]` solved this.

(Add trailing slash)

**Comment by james-martin-jd** [comment]
I believe the trailing slash requirement for containers is actually a Node Solid Server requirement, and not anything to do with LDFlex specifically?

**Comment by RubenVerborgh** [comment]
It's NSS indeed. The URI of the container is the thing with the slash.
