### ISSUE TITLE
how to externalize query-ldflex in shighl webpack.config.js ?

### ISSUE THREAD

**Issue by scenaristeur** [solid/query-ldflex#57]
Hi @RubenVerborgh ,

I'm working on [Shighl ](https://github.com/scenaristeur/shighl)a S-olid HIGH L-evel API based on query-ldflex, 
this is a tool with some high level function to interact with POD session, inbox, longchat and I need to externalize query-ldflex, but I don't know on to configure Webpack for that. 

I've tried some 

```
  externals: {
    'solid-auth-cli': 'null',
 '@solid/query-ldflex': 'query-ldflex',
    /*  '@solid/query-ldflex': {
    commonjs: 'query-ldflex',
    commonjs2: 'query-ldflex',
    amd: 'query-ldflex',
    root: 'data'
  },*/
```
but I got this error "
TypeError: _solid_query_ldflex__WEBPACK_IMPORTED_MODULE_20___default.a is undefined" 

I can import vendor/solid-query-ldflex.bundle.js on this page https://scenaristeur.github.io/shighl/externalize.html but my lib is always ~10Mo.
Do you have an idea ? Thxs

**Comment by RubenVerborgh** [comment]
Hi @scenaristeur,

Since LDflex for Solid is exposed as `window.solid.data`, you will want something like:

```
      '@solid/query-ldflex': {
        root: ['solid', 'data'],
        commonjs: '@solid/query-ldflex', // not used, but needed for config
        commonjs2: '@solid/query-ldflex',  // not used, but needed for config
      },
```

**Comment by scenaristeur** [comment]
thxs it's perfect and works like a charm ! https://scenaristeur.github.io/shighl/instances.html
