### ISSUE TITLE
Updating a mail node

### ISSUE THREAD

**Issue by javiergarber** [solid/query-ldflex#66]
Hello,
this probably is a silly question but im trying to update de value of the mail address nodes. Currently i'm doing it by setting the value of the corresponding node, the thing is what I'm writing is a literal, using this 
`  for await (const emailId of me["vcard:hasEmail"]) {
    let email = await data[emailId}].vcard$value.set(
      'mailto:mail@email.com'
    );
}`
This previously shown is not the exact code I'm using but you get what im trying to do, just access the correct node and change its value.
I'm not sure what is the exact type of <mailto:mail@email.com> node so what I'm obtaining is something like `:id1588664791865 n:value "mailto:mail@email.com".` and not the expected between <> value. How would be the appropriate way to do it? Thank you in advance

**Comment by RubenVerborgh** [comment]
You'll want a `NamedNode` there, so `set(namedNode('mailto:mail@email.com'))`.

**Comment by javiergarber** [comment]
Thank you so much, I recently started using this library so I don't know how it exactly works, guess I need practice.

**Comment by RubenVerborgh** [comment]
And documentation… we'll work on that 🙂
