### ISSUE TITLE
@ldflex/rdflib not a dependency in package.json: clarify in the README

### ISSUE THREAD

**Issue by bjdmeest** [solid/query-ldflex#67]
My TS project using @solid/query-ldflex/lib/exports/rdflib wouldn't compile without additionally installing @ldflex/rdflib myself. I guess it should be part of this repo's package.json?

**Comment by RubenVerborgh** [comment]
It’s intended behavior, in the sense that I consider Comunica the default. Usage of the rdflib version is only recommended for projects that already have rdflib and do not want another engine. Adding it in dependencies would force its installation everywhere (and it has some larger dependencies).

But documenting that in the README would probably be good. Would that work?
