### ISSUE TITLE
"ReferenceError: setImmediate is not defined" occurs when query data.

### ISSUE THREAD

**Issue by sunjae-kim** [solid/query-ldflex#68]
Hi, I am using Next.js due to SSR.

Using node version 12.14.0 and below is my code.

```js
import React, { useState, useEffect } from 'react';
import { withWebId } from '@solid/react';
import data from '@solid/query-ldflex';

const MyPage = ({ webId }) => {
  const [name, setName] = useState('');

  const getProfileData = async () => {
    const user = data[webId];
    const nameLd = await user.vcard_fn;
    setName(nameLd.value);
  };

  useEffect(() => {
    if (webId) getProfileData();
  }, [webId]);

  return (
    <div>
      <p>Your Web Id is {webId}</p>
      <p>Your name is {name}</p>
    </div>
  );
};

export default withWebId(MyPage);
```

Sometimes it works, but the most of the time it gives `ReferenceError: setImmediate is not defined`.

<img width="878" alt="Screen Shot 2020-05-08 at 17 06 03" src="https://user-images.githubusercontent.com/40228715/81385494-623f1780-914e-11ea-9e10-356b49255cb0.png">

Is there any solution for this?

**Comment by RubenVerborgh** [comment]
> Using node version 12.14.0

From the screenshot it appears you are using a browser though 🙂

Did you webpack your code?

**Comment by sunjae-kim** [comment]
Yes I webpacked my code and opened it with browser.

**Comment by RubenVerborgh** [comment]
Then I will need your webpack config, because webpack is supposed to inject `setImmediate`.

**Comment by sunjae-kim** [comment]
Thank you Ruben!

I found that `setImmediate` was set to false in my webpack setting.

Just added below code in `next.config.js`, it worked like a charm 😀

```js
webpack(config, options) {
  config.node.setImmediate = true;
  ...
}
```

**Comment by RubenVerborgh** [comment]
Super!
