### ISSUE TITLE
Support the creation of new resources

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/query-ldflex#7]
See https://github.com/Inrupt-inc/solid-react-sdk/issues/2

**Comment by james-martin-jd** [comment]
Ideally this would include support to create new files of any type, not just .acl files, although that will be a specific requirement for the react SDK 0.4.0.

Added a milestone for SDK version 0.3.0, which is targeting a late February release, but will begin work soon.

**Comment by joachimvh** [comment]
What exactly is meant with the creation of any file type? From what I can see it already is possible to write to non-existent paths, causing that file to be created in the pod, so what exactly is required then? (Besides the acl files that is)

**Comment by RubenVerborgh** [comment]
@james-martin-jd Is the use case creating a blank document?
Because it is actually supported to create documents by just adding data to them:
https://solid.github.io/ldflex-playground/#%5Bhttps%3A%2F%2Frubenverborgh.inrupt.net%2Fpublic%2Fyour-document-here%23note%5D.name.add('A%20note%20in%20a%20new%20document')

**Comment by RubenVerborgh** [comment]
Closed by #60.
