### ISSUE TITLE
Enable support for reading/writing local data stores

### ISSUE THREAD

**Issue by james-martin-jd** [solid/query-ldflex#8]
Most projects will likely have local configuration options, such as i18n or projects settings, and we would like to store this in ttl if possible. Currently, though, we can't read in from a local file. We would like to enable local file support, so we can begin using local ttl files.

I've marked this as SDK 0.3.0, which will begin work very soon.

**Comment by RubenVerborgh** [comment]
The above proposal has been implemented by #11 and will be released as v2.1.0.
